{
 "title": "General Monitoring",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Logs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "SMPP Logs",
     "type": "logs",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 49 },
     "targets": [
      {
       "expr": "{namespace=\"default\", service_name=\"smpp-service\"} | json | line_format \"{{._timestamp}} {{.log_level}} {{.message}}\""
      }
     ]
    },
    {
     "title": "Channel Selector Logs",
     "type": "logs",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 58 },
     "targets": [
      {
       "expr": "{namespace=\"default\", service_name=\"channel-selector\"} | json | line_format \"{{._timestamp}} {{.log_level}} {{.message}}\""
      }
     ]
    },
    {
     "title": "Channel Adapter Logs",
     "type": "logs",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 67 },
     "targets": [
      {
       "expr": "{namespace=\"default\", service_name=\"channel-adapter\"} | json | line_format \"{{._timestamp}} {{.log_level}} {{.message}}\""
      }
     ]
    }
   ]
  },
  {
   "title": "Traces",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Long Traces",
     "type": "table",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 34 },
     "targets": [
      {
       "filters": [
        { "id": "61c2e9e4", "operator": "=", "scope": "span" },
        {
         "id": "service-name",
         "operator": "=",
         "scope": "resource",
         "tag": "service.name",
         "value": [ "smpp-service" ],
         "valueType": "string"
        },
        {
         "id": "min-duration",
         "operator": ">",
         "tag": "duration",
         "value": "1s",
         "valueType": "duration"
        },
        { "id": "duration-type", "value": "trace" }
       ],
       "limit": 20,
       "query": "{s}",
       "tableType": "traces"
      }
     ]
    },
    {
     "title": "All traces",
     "type": "table",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 44 },
     "targets": [
      {
       "filters": [
        { "id": "61c2e9e4", "operator": "=", "scope": "span" },
        {
         "id": "service-name",
         "operator": "=",
         "scope": "resource",
         "tag": "service.name",
         "value": [ "smpp-service" ],
         "valueType": "string"
        }
       ],
       "limit": 20,
       "query": "{s}",
       "tableType": "traces"
      }
     ]
    }
   ]
  },
  {
   "title": "Service Latency Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "SMPP Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum(rate(traces_spanmetrics_latency_bucket{service=\"smpp-service\", span_name=\"handle-smpp-request\"}[2m])) by (le))",
       "legendFormat": "p50"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(traces_spanmetrics_latency_bucket{service=\"smpp-service\", span_name=\"handle-smpp-request\"}[2m])) by (le))",
       "legendFormat": "p95"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(traces_spanmetrics_latency_bucket{service=\"smpp-service\", span_name=\"handle-smpp-request\"}[2m])) by (le))",
       "legendFormat": "p99"
      }
     ]
    },
    {
     "title": "Channel Selector Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum(rate(traces_spanmetrics_latency_bucket{service=\"channel-selector\", span_name=\"message-inbound receive\"}[2m])) by (le))",
       "legendFormat": "p50"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(traces_spanmetrics_latency_bucket{service=\"channel-selector\", span_name=\"message-inbound receive\"}[2m])) by (le))",
       "legendFormat": "p95"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(traces_spanmetrics_latency_bucket{service=\"channel-selector\", span_name=\"message-inbound receive\"}[2m])) by (le))",
       "legendFormat": "p99"
      }
     ]
    },
    {
     "title": "Channel Adapter Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum(rate(traces_spanmetrics_latency_bucket{service=\"channel-adapter\", span_name=\"message-outbound receive\"}[2m])) by (le))",
       "legendFormat": "p50"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(traces_spanmetrics_latency_bucket{service=\"channel-adapter\", span_name=\"message-outbound receive\"}[2m])) by (le))",
       "legendFormat": "p95"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(traces_spanmetrics_latency_bucket{service=\"channel-adapter\", span_name=\"message-outbound receive\"}[2m])) by (le))",
       "legendFormat": "p99"
      }
     ]
    }
   ]
  }
 ]
}
{
 "title": "Monitoring Overhead",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "vCPU",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"default\", container=\"channel-selector\", pod=~\"channel-selector-.*\"}[4m])) by (pod)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"default\", container=\"channel-selector-nomon\"}[4m])) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "vCPU Ratio",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"default\", container=\"channel-selector\"}[4m]))/sum(rate(container_cpu_usage_seconds_total{namespace=\"default\", container=\"channel-selector-nomon\"}[4m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{pod=~\"channel-selector-.*\", pod!~\".*nomon.*\"}[4m])) by (pod)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{pod=~\"channel-selector-nomon.*\"}[4m])) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network Ratio",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{pod=~\"channel-selector-.*\", pod!~\".*nomon.*\"}[4m])) / sum(rate(container_network_transmit_bytes_total{pod=~\"channel-selector-nomon.*\"}[4m]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}