---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  namespace: rabbitmq
spec:
  selector:
    matchLabels:
      app: rabbitmq
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
      - image: rabbitmq:3.13.7-management-alpine
        name: rabbitmq
        ports:
        - containerPort: 5672
          name: rabbit-1
        - containerPort: 15672
          name: rabbit-2
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: rabbitmq
spec:
  ports:
  - port: 5672
  selector:
    app: rabbitmq
